name: Deploy React Application
on:
  push:
    paths:
      - "client/**"
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t minhvnqh/react-app -f client/Dockerfile client --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}'
      - name: Publish Image to docker hub
        run: docker push minhvnqh/react-app:latest
  deploy:
    needs: build
    runs-on: react
    steps:
      - name: Pull image from docker hub
        run: docker pull minhvnqh/react-app:latest
      - name: Delete old container
        run: docker rm -f react-app-container
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name react-app-container minhvnqh/react-app
